{% set version = "master" %}

package:
  name: cmvs
  version: {{ version }}

source:
  fn: cmvs-{{ version }}.tar.gz
  url: https://github.com/edgarriba/CMVS-PMVS/archive/{{ version }}.tar.gz
  sha256: 155ba2e0bb6950aa8b3246e5b3f0b052bf72d5bbe9b0994185a09dd17e7b6de2

build:
    number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - boost
    - jpeg
    - libpng
    - libtiff

about:
  home: https://www.di.ens.fr/cmvs/
  license: GPL
  summary: Clustering Views for Multi-view Stereo

extra:
  recipe-maintainers:
    - v-turin
